# Generated by Django 2.0.3 on 2018-03-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score', models.BigIntegerField(default=0, editable=False)),
                ('datePublished', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['score'],
            },
        ),
    ]
